---
- hosts: webserver
  remote_user: test5000
  become: yes
  tasks:
      - name: Install httpd
        command: yum install -y httpd 
        args:
              creates: /var/www/html
      - name: create index.html file
        shell: echo "testing" > /var/www/html/index.html 
      - name: start httpd service
        raw:  service httpd start
      - name: execute abc script
        script: ./abc.sh
        args:
              creates: /home/test5000/xyz
