---
- hosts: "{{host}}"
  remote_user: test5000
  become: yes
  vars:
     pkg: httpd
  vars_files:
     - abc.yml
  vars_prompt:
     - name: pkg2
       prompt: enter package name
       private: no 
  tasks:
      - name: Install httpd
        yum: name={{pkg}} state=installed
      - name: Install {{pkg1}} 
        yum: name={{pkg1}} state=installed
      - name: Install {{pkg2}} 
        yum: name={{pkg2}} state=installed
      - name: create index.html file
        copy: src=index.html dest=/var/www/html
        notify: Restart httpd 
      - name: start httpd service
        service: name={{pkg}} state=started
  handlers:
      - name: Restart httpd
        service: name=httpd state=restarted
