--- # Example of Tomcat Installation 
- hosts: server3
  remote_user: test5000
  become: yes
  gather_facts: yes
  tasks:
   - name: Download Tomcat
     get_url: url=http://www-us.apache.org/dist/tomcat/tomcat-7/v7.0.82/bin/apache-tomcat-7.0.82.tar.gz  dest=/tmp
   - name: Create tomcat folder
   #  command:  mkdir /usr/local/tomcat
     file: path=/usr/local/tomcat state=directory  
   - name: Extract archive
     unarchive: src=/tmp/apache-tomcat-7.0.82.tar.gz dest=/usr/local/tomcat copy=no
   - name: create tomcat users
     copy: src=/home/test5000/tomcat-users.xml dest=/usr/local/tomcat/apache-tomcat-7.0.82/conf/
   - name: deplog app
     copy: src=sample.war dest=/usr/local/tomcat/apache-tomcat-7.0.82/webapps
   - name: Start Tomcat
     command: nohup  /usr/local/tomcat/apache-tomcat-7.0.82/bin/startup.sh &
