---
- hosts: webserver
  remote_user: test5000
  become: yes
  tasks:
      - name: Install httpd
        yum: name=httpd state=installed
        when: ansible_os_family == "RedHat"
      - name: install apache2
        apt: name=apache2 state=installed
        when: ansible_os_family == "Debian"
      - name: create index.html file
        copy: src=index.html dest=/var/www/html
      - name: start httpd service
        service: name=httpd state=started
